--RDCC-1387 AAC Roles
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (38, 'pui-caa', 'SIDAM_ROLE', 'pui caa');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (39, 'caseworker-caa', 'CCD_ROLE', 'caseworker caa');