INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (20, 'PROBATE', 'JURISD_ID', 'Services (grant of representation, caveats, will lodgment, standing search, settlers, pre lodgement)');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (21, 'DIVORCE', 'JURISD_ID', 'Family Divorce: dissolution of marriage');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (22, 'BULKSCAN', 'JURISD_ID', 'Bulk Scanning');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (23, 'bulkscan', 'JURISD_ID', 'Bulk Scanning');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (24, 'IA', 'JURISD_ID', 'Immigration & Asylum');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (25, 'CMC', 'JURISD_ID', 'CMC Jurisdiction');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (26, 'PUBLICLAW', 'JURISD_ID', 'Public Law DRAFT');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (27, 'EMPLOYMENT', 'JURISD_ID', 'Employment');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (28, 'AUTOTEST1', 'JURISD_ID', 'Content for the Test Jurisdiction');