targetInstance: ${TEST_URL:http://localhost:8090}

s2s-url: ${S2S_URL_FOR_TESTS:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}

s2s-name: rd_professional_api
scope-name: openid profile roles manage-user create-user search-user

idam.api.url: ${IDAM_URL:https://idam-api.aat.platform.hmcts.net}
oauth2-client-secret: ${OAUTH2_CLIENT_SECRET:}
idam.auth.clientId: ${OAUTH2_CLIENT_ID:}
idam.auth.redirectUrl: ${OAUTH2_REDIRECT_URI:https://rd-professional-api-aat.service.core-compute-aat.internal/oauth2redirect}
s2s-secret: ${PROFESSIONAL_API_S2S_SECRET:}
spring.jpa.properties.hibernate.default_schema: dbrefdata
## spring.flyway.enabled: false
## Secure roles configuration 1
prd.security.roles.hmcts-admin: prd-admin
prd.security.roles.caseworker-civil-admin: caseworker-civil-admin
prd.security.roles.pui-user-manager: pui-user-manager
prd.security.roles.pui-organisation-manager: pui-organisation-manager
prd.security.roles.pui-finance-manager: pui-finance-manager
prd.security.roles.pui-case-manager: pui-case-manager
prd.security.roles.pui-caa: pui-caa
prd.security.roles.caseworker-caa: caseworker-caa
prd.security.roles.prd-aac-system: prd-aac-system
prd.security.roles.caseworker: caseworker
prd.security.roles.citizen: citizen


oauth2.redirect.uri: test
oauth2.client.id: test
oauth2.client.secret: test
test.user.password: test







