java:
  devmemoryRequests: 1024Mi
  devcpuRequests: 1000m
  devmemoryLimits: 2048Mi
  devcpuLimits: 2500m
    # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_HOST: rd-professional-api-postgres-db-v16-{{ .Values.global.environment }}.postgres.database.azure.com
    POSTGRES_USERNAME: pgadmin
