professional-user-details-start-route: direct:Professional-UserDetails
professional-user-details-route-task: userDetailsRouteTask
professional-user-details-routes-to-execute: professional-user-details-load
start-route: direct:PRD
route:
  #Route: professional-user-details-load
  professional-user-details-load:
    id: professional-user-details-load
    file-name: BulkCustomerIDs.csv
    table-name: bulk_customer
    truncate-sql:
      sql:truncate table bulk_customer
    insert-sql:
      sql:insert into bulk_customer (organisation_id,bulk_customer_Id,sidam_id,pba)
      values (:#organisationId,:#bulkCustomerId,:#sidamId,:#sidamId,:#pba)
    blob-path:
      azure-blob://${azure.storage.account-name}/prd-ref-data/BulkCustomerIDs.csv?credentials=#credsreg&operation=updateBlockBlob
    processor-class: userDetailsProcessor
    mapper-class: userDetailsMapper
    csv-binder-object: UserDetails
    csv-headers-expected: id,first_name,last_name
    header-validation-enabled: true

