professional-user-details-start-route: direct:Professional-UserDetails
professional-user-details-route-task: userDetailsRouteTask
professional-user-details-routes-to-execute: professional-user-details-load
route:
  #Route: professional-user-details-load
  professional-user-details-load:
    id: professional-user-details-load
    file-name: BulkCustomerIDs.csv
    table-name: bulk_customer_details
    truncate-sql:
      sql:truncate dbrefdata.table bulk_customer_details
    insert-sql:
      sql:insert into dbrefdata.bulk_customer_details (id,organisation_id,bulk_customer_id,sidam_id,pba_number)
      values (:#id, :#organisation_id,:#bulk_customer_id,:#sidam_id,:#pba_number)
    blob-path:
      azure-blob://${azure.storage.account-name}/rd-prd-data/BulkCustomerIDs.csv?credentials=#credsreg&operation=updateBlockBlob
    processor-class: BulkCustomerDetailsProcessor
    mapper-class: BulkCustomerDetailsMapper
    csv-binder-object: BulkCustomerDetails
    csv-headers-expected: Organisation_ID,Bulk_Customer_ID,Sidam_ID,PBA
    header-validation-enabled: true

