CREATE SCHEMA IF NOT EXISTS dbrefdata;

CREATE TABLE organisation
(
  ID              VARCHAR(36)  NOT NULL,
  NAME            VARCHAR(255) NOT NULL,
  LAST_UPDATED    TIMESTAMP default current_timestamp,
  STATUS          VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE professional_user
(
  ID              VARCHAR(36)  NOT NULL,
  FIRST_NAME      VARCHAR(255) NOT NULL,
  LAST_NAME       VARCHAR(255) NOT NULL,
  EMAIL_ADDRESS   VARCHAR(255) NOT NULL,
  STATUS          VARCHAR(20) NOT NULL,
  ORGANISATION_ID VARCHAR(36)  NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ORGANISATION_ID) REFERENCES organisation (id)
);
