CREATE SCHEMA IF NOT EXISTS dbrefdata;

CREATE TABLE organisation
(
  ID              UUID,
  NAME            VARCHAR(255) NOT NULL,
  LAST_UPDATED    TIMESTAMP,
  CREATED         TIMESTAMP NOT NULL,
  STATUS          VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE professional_user
(
  ID                 UUID,
  FIRST_NAME         VARCHAR(255) NOT NULL,
  LAST_NAME          VARCHAR(255) NOT NULL,
  EMAIL_ADDRESS      VARCHAR(255) NOT NULL,
  STATUS             VARCHAR(50) NOT NULL,
  ORGANISATION_ID    UUID NOT NULL,
  PAYMENT_ACCOUNT_ID UUID,
  LAST_UPDATED       TIMESTAMP,
  CREATED            TIMESTAMP NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ORGANISATION_ID) REFERENCES organisation (id)
);

CREATE TABLE payment_account
(
  ID                   UUID,
  PBA_NUMBER           VARCHAR(255) NOT NULL UNIQUE,
  ORGANISATION_ID      UUID,
  PROFESSIONAL_USER_ID UUID,
  LAST_UPDATED         TIMESTAMP NOT NULL,
  CREATED              TIMESTAMP NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ORGANISATION_ID) REFERENCES organisation (id),
  FOREIGN KEY (PROFESSIONAL_USER_ID) REFERENCES professional_user (id)
);

ALTER TABLE professional_user ADD FOREIGN KEY (PAYMENT_ACCOUNT_ID) REFERENCES payment_account (id);