-- RDCC-120
ALTER TABLE PROFESSIONAL_USER ADD COLUMN USER_IDENTIFIER VARCHAR(32) NOT NULL;

ALTER TABLE PROFESSIONAL_USER ADD CONSTRAINT USER_IDENTIFIER_UQ UNIQUE (USER_IDENTIFIER);

-- RDCC-171 DML FOR ENUM TABLE
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (0, 'PUI_USER_MANAGER', 'PRD_ROLE', 'Manage Professional users');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (1, 'PUI_ORGANISATION_MANAGER', 'PRD_ROLE', 'Manage professional organisations');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (2, 'PUI_FINANCE_MANAGER', 'PRD_ROLE', 'Manage finance');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (3, 'PUI_CASE_MANAGER', 'PRD_ROLE', 'Manage cases');