CREATE TABLE payment_account
(
  ID              UUID,
  PBA_NUMBER      VARCHAR(255) NOT NULL UNIQUE,
  ORGANISATION_ID UUID,
  USER_ID         UUID,
  LAST_UPDATED    TIMESTAMP NOT NULL,
  CREATED         TIMESTAMP NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ORGANISATION_ID) REFERENCES organisation (id),
  FOREIGN KEY (USER_ID) REFERENCES professional_user (id)
);