--RDCC-190

ALTER TABLE ORGANISATION DROP COLUMN ORGANISATION_IDENTIFIER;

ALTER TABLE ORGANISATION ADD COLUMN ORGANISATION_IDENTIFIER VARCHAR(7);

ALTER TABLE ORGANISATION ADD CONSTRAINT ORGANISATION_IDENTIFIER_UQ1 UNIQUE (ORGANISATION_IDENTIFIER);