--RDCC-1387 AAC Roles
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (36, 'pui-caa', 'SIDAM_ROLE', 'pui caa');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (37, 'caseworker-caa', 'CCD_ROLE', 'caseworker caa');
