
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (10, 'PROBATE', 'JURISD_ID', 'Services (grant of representation, caveats, will lodgment, standing search, settlers, pre lodgement)');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (11, 'SSCS', 'JURISD_ID', 'Social Security and Child Support');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (12, 'DIVORCE', 'JURISD_ID', 'Family Divorce: dissolution of marriage');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (13, 'BULKSCAN', 'JURISD_ID', 'Bulk Scanning');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (14, 'IA', 'JURISD_ID', 'Immigration & Asylum');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (15, 'CMC', 'JURISD_ID', 'CMC Jurisdiction');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (16, 'PUBLICLAW', 'JURISD_ID', 'Public Law DRAFT');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (17, 'EMPLOYMENT', 'JURISD_ID', 'Employment');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (18, 'AUTOTEST1', 'JURISD_ID', 'Content for the Test Jurisdiction');