
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (10, 'PROBATE', 'JURISD_ID', 'PROBATE');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (11, 'SSCS', 'JURISD_ID', 'SSCS');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (12, 'DIVORCE', 'JURISD_ID', 'DIVORCE');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (13, 'BULKSCAN', 'JURISD_ID', 'BULKSCAN');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (14, 'IA', 'JURISD_ID', 'IA');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (15, 'CMC', 'JURISD_ID', 'CMC');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (16, 'PUBLICLAW', 'JURISD_ID', 'PUBLICLAW');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (17, 'EMPLOYMENT', 'JURISD_ID', 'EMPLOYMENT');
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (18, 'AUTOTEST1', 'JURISD_ID', 'AUTOTEST1');