UPDATE PRD_ENUM SET ENUM_NAME = 'Probate' WHERE ENUM_CODE=10;
UPDATE PRD_ENUM SET ENUM_NAME = 'SSCS' WHERE ENUM_CODE=11;
UPDATE PRD_ENUM SET ENUM_NAME = 'Divorce' WHERE ENUM_CODE=12;
UPDATE PRD_ENUM SET ENUM_NAME = 'Bulk Scanning' WHERE ENUM_CODE=13;
UPDATE PRD_ENUM SET ENUM_NAME = 'Immigration & Asylum' WHERE ENUM_CODE=14;
UPDATE PRD_ENUM SET ENUM_NAME = 'Civil Money Claims' WHERE ENUM_CODE=15;
UPDATE PRD_ENUM SET ENUM_NAME = 'Public Law' WHERE ENUM_CODE=16;
UPDATE PRD_ENUM SET ENUM_NAME = 'Employment' WHERE ENUM_CODE=17;
UPDATE PRD_ENUM SET ENUM_NAME = 'Family public law and adoption', ENUM_DESC = 'Family public law and adoption'  WHERE ENUM_CODE=18;
INSERT INTO PRD_ENUM (ENUM_CODE, ENUM_NAME, ENUM_TYPE, ENUM_DESC) VALUES (19, 'Civil enforcement and possession', 'JURISD_ID', 'Civil enforcement and possession');

