ALTER TABLE organisation ADD CONSTRAINT SRA_ID_UQ1 UNIQUE (SRA_ID);

ALTER TABLE professional_user DROP COLUMN status;

ALTER TABLE professional_user ADD COLUMN deleted timestamp;

ALTER TABLE professional_user DROP CONSTRAINT EMAIL_ADDRESS_UQ1;

ALTER TABLE professional_user ADD CONSTRAINT EMAIL_ADDRESS_UQ1 UNIQUE (EMAIL_ADDRESS, DELETED);